rate_system\Scripts\pip.exe install flask
rate_system\Scripts\pip.exe install flask-login
rate_system\Scripts\pip.exe install flask-openid
rate_system\Scripts\pip.exe install flask-mail
rate_system\Scripts\pip.exe install sqlalchemy
rate_system\Scripts\pip.exe install flask-sqlalchemy
rate_system\Scripts\pip.exe install sqlalchemy-migrate
rate_system\Scripts\pip.exe install flask-whooshalchemy
rate_system\Scripts\pip.exe install flask-wtf
rate_system\Scripts\pip.exe install pytz
rate_system\Scripts\pip.exe install flask-babel
rate_system\Scripts\pip.exe install flup
rate_system\Scripts\pip.exe install psycopg2
rate_system\Scripts\pip.exe install psycopg2-binary
rate_system\Scripts\pip install beautifulsoup4
