pip3 install flask
pip3 install flask-login
pip3 install flask-openid
pip3 install flask-mail
pip3 install sqlalchemy
pip3 install flask-sqlalchemy
pip3 install sqlalchemy-migrate
pip3 install flask-whooshalchemy
pip3 install flask-wtf
pip3 install pytz
pip3 install flask-babel
pip3 install flup
pip3 install psycopg2
pip3 install psycopg2-binary
pip3 install beautifulsoup4
pip3 install argon2-cffi
